#!/bin/sh

touch $HOME/.psqlrc.local

if [ ! -e $HOME/.vim/autoload/plug.vim ]; then
  curl -fLo $HOME/.vim/autoload/plug.vim --retry 1 --max-time 10 --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
if [[ $- == *i* ]]; then
	vim -u $HOME/.vimrc.bundles +PlugInstall +PlugClean! +qa
fi
